language: node_js
dist: bionic
node_js:
  - 12
addons:
  apt:
    packages:
    # These are required to run webkit
    - libwoff1
    - libopus0
    - libwebp6
    - libwebpdemux2
    - libenchant1c2a
    - libgudev-1.0-0
    - libsecret-1-0
    - libhyphen0
    - libgdk-pixbuf2.0-0
    - libegl1
    - libgles2
    - libevent-2.1-6
    - libnotify4
    - libxslt1.1
    - libvpx5
    # This is required to run chromium
    - libgbm1
install:
- npm --production=false install
jobs:
  include:
    - stage: test
      script:
      - node index.js
