language: node_js
dist: trusty
node_js:
  - 10
env:
  # install browser binaries in node_modules
  - NODE_ENV=production PLAYWRIGHT_BROWSERS_PATH=0
install:
- npm --production=false install
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      script:
      - DEBUG=pw:browser* node index.js
