language: node_js
dist: trusty
node_js:
  - 10
env:
  - NODE_ENV=production
install:
- npm --production=false install
jobs:
  include:
    - stage: test
      script:
      - DEBUG=pw:browser* node index.js
