name: "tests"
on:
  push:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1

    - uses: microsoft/playwright-github-action@v1.2.0

    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: node index.js
