name: "tests"
on:
  push:
    branches:
      - master

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1

    - uses: microsoft/playwright-github-action@v1

    - name: Run Playwright
      run: npm install && node index.js
